services:
  django-web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: >
      bash -c "
        python manage.py migrate --no-input &&
        python manage.py runserver 0.0.0.0:8000
      "